/** @format */

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import UserInfo from '@/components/ui/userInfo'
import RoutingButton from '@/components/ui/routingButton'
import { signout } from './authentication/actions'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en' suppressHydrationWarning className='h-full'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-full`}
            >
                <div className='flex flex-row fixed z-10 items-center bg-green-400 w-full py-3'>
                    <div className='border p-1 mx-5 border-solid border-black bg-green-300 hover:bg-slate-200 rounded-ls'>
                        <RoutingButton
                            displayName='Log out'
                            onClick={signout}
                        ></RoutingButton>
                    </div>
                    <div>
                        <UserInfo></UserInfo>
                    </div>
                </div>

                {children}

                {/* <div className='flex flex-col min-h-screen'>
                    <div className='flex flex-row justify-between items-center p-5 bg-gray-100'>
                        <div className='border p-1 mx-5 border-solid border-black bg-green-300 hover:bg-slate-200 rounded-ls'>
                            <RoutingButton displayName='Log out'></RoutingButton>
                        </div>
                        <div>
                            <UserInfo></UserInfo>
                        </div>
                    </div>

                    <div className='flex-grow flex justify-center items-center mb-20'>
                        {children}
                    </div>
                </div> */}
            </body>
        </html>
    )
}
